language: ruby
rvm:
  - 2.4.3
cache:
  directories:
    - vendor/bundle
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --path vendor/bundle --without production --jobs=3 --retry=1
script:
  - bundle exec rspec spec/

