source 'https://rubygems.org'

gem 'byebug'
gem 'json'
gem 'selenium-webdriver'
gem 'webdriver-firefox'
gem 'chromedriver-helper'
gem 'geckodriver-helper'
gem 'rspec'
gem 'capybara'
gem 'chromedriver-helper'
gem 'pry'
gem 'dotenv'